name: Develop Run Unit Tests

on:
  push:
    branches: [ develop ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Add debug key
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.DEBUG_KEYSTORE }}
          passphrase: ${{ secrets.DEBUG_KEYSTORE_PASSPHRASE }}
          filename: "settings/keystore/debug.jks"

      - name: Add google service file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.GOOGLE_SERVICE_FILE }}
          passphrase: ${{ secrets.GOOGLE_SERVICE_PASSPHRASE }}
          filename: "application/src/dev/google-services.json"

      - name: Start tests
        run: ./gradlew testDevDebugUnitTest
