name: Develop Run Ui Tests

on:
  push:
    branches: [ develop ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Add debug key
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.DEBUG_KEYSTORE }}
          passphrase: ${{ secrets.DEBUG_KEYSTORE_PASSPHRASE }}
          filename: "settings/keystore/debug.jks"

      - name: Add google service file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.GOOGLE_SERVICE_FILE }}
          passphrase: ${{ secrets.GOOGLE_SERVICE_PASSPHRASE }}
          filename: "application/src/dev/google-services.json"

      - name: Build the app
        run: ./gradlew :application:assembleDevDebug

      - name: Build the instrumentation tests apk
        run: ./gradlew :application:assembleDevDebugAndroidTest

      - name: Auth Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Start UI tests
        run: gcloud firebase test android run
              --type instrumentation
              --use-orchestrator
              --app application/build/outputs/apk/dev/debug/application-dev-debug.apk
              --test application/build/outputs/apk/androidTest/dev/debug/application-dev-debug-androidTest.apk
              --device model=Pixel2,version=29,orientation=portrait
              --environment-variables clearPackageData=true
