name: Push Develop Workflow

on:
  push:
    branches: [ develop ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Create gradle properties
        run: echo $GRADLE_PROPERTIES > utility/gradle.properties
      - name: Add debug key
        run: echo "${{ secrets.DEBUG_KEYSTORE }}" > settings/keystore/debug.jks.asc
             gpg --batch --passphrase "${{ secrets.DEBUG_KEYSTORE_PASSPHRASE }}" -d -o settings/keystore/debug.jks settings/keystore/debug.jks.asc
      - name: Add firebase service credentials file
        run: echo "${{ secrets.DEBUG_FIREBASE_CREDENTIALS_FILE }}" > settings/distribute/firebase-app-distribution-dev.json.asc
             gpg --batch --passphrase "${{ secrets.DEBUG_FIREBASE_CREDENTIALS_PASSPHRASE }}" -d -o settings/distribute/firebase-app-distribution-dev.json settings/distribute/firebase-app-distribution-dev.json.asc
      - name: Build the app
        run: ./gradlew clean :application-main:assembleDevDebug
      - name: Start tests
        run: ./gradlew testDevDebugUnitTest 
      - name: Send to testers
        run: ./gradlew :application-main:appDistributionUploadDevDebug
