name: Pull Request Workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create gradle properties
        run: echo $GRADLE_PROPERTIES > utility/gradle.properties

      - name: Add debug key
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.DEBUG_KEYSTORE }}
          passphrase: ${{ secrets.DEBUG_KEYSTORE_PASSPHRASE }}
          filename: "settings/keystore/debug.jks"

      - name: Add firebase service credentials file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
          passphrase: ${{ secrets.FIREBASE_CREDENTIALS_PASSPHRASE }}
          filename: "settings/distribute/firebase-app-distribution.json"

      - name: Add google service file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.GOOGLE_SERVICE_FILE }}
          passphrase: ${{ secrets.GOOGLE_SERVICE_PASSPHRASE }}
          filename: "application/src/dev/google-services.json"

      - name: Build the app
        run: ./gradlew :application:assembleDevDebug

      - name: Start tests
        run: ./gradlew testDevDebugUnitTest
