name: Push Master Workflow

on:
  push:
    tags:
      - 'v*'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read Release Notes
        id: release_notes
        uses: juliangruber/read-file-action@v1
        with:
          path: settings/distribute/whatsnew/whatsnew-en-US

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            ${{ steps.release_notes.outputs.content }}
          draft: false
          prerelease: false

      - name: Create gradle properties
        run: echo $GRADLE_PROPERTIES > utility/gradle.properties

      - name: Add release key
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.RELEASE_KEYSTORE }}
          passphrase: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          filename: "settings/keystore/release.jks"

      - name: Add keystore properties file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.KEYSTORE_PROPERTIES_FILE }}
          passphrase: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
          filename: "settings/keystore/keystore.properties"

      - name: Add firebase service credentials file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
          passphrase: ${{ secrets.FIREBASE_CREDENTIALS_PASSPHRASE }}
          filename: "settings/distribute/firebase-app-distribution.json"

      - name: Add google service file
        uses: JakubMosakowski/secret-into-file-action@v1.0.0
        with:
          secret: ${{ secrets.GOOGLE_SERVICE_FILE }}
          passphrase: ${{ secrets.GOOGLE_SERVICE_PASSPHRASE }}
          filename: "application/src/prod/google-services.json"

      - name: Build the app
        run: ./gradlew clean :application:bundleProdRelease

      - name: Upload to play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: settings/distribute/firebase-app-distribution.json
          packageName: com.jakmos.itemistevolved
          releaseFiles: application/build/outputs/bundle/prodRelease/application-prod-release.aab
          track: internal
          whatsNewDirectory: settings/distribute/whatsnew
          mappingFile: application/build/outputs/mapping/prodRelease/mapping.txt
